services:
  - type: web
    name: protein-planet
    env: php
    plan: free
    buildCommand: echo "No build needed for PHP"
    startCommand: php -S 0.0.0.0:$PORT -t frontend
    healthCheckPath: /index.php
    envVars:
      - key: PHP_VERSION
        value: "8.1"

